/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0b42b35e-a866-4a1e-b4f6-551cebb281ec",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dZiWFMooI",
    "aws_user_pools_web_client_id": "3ogtq8ne5le4p6hckbnsonq7m5",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://fdktzgdfuzfvzbdrxt3iytozze.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-iqi3nefosjcrtefzvu5cvnij4i",
    "aws_user_files_s3_bucket": "projectboards77b21c06c37841ddbdea3f8bed8abc9c39290-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
